import type { Metadata } from "next";
import { ThemeProvider } from "next-themes"
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import MySidebar from "./sidebar";
import { NavigationMenuDemo } from "./nav";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'], display: 'swap' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
    <body className={`${inter.className} ${geistMono.variable} antialiased`}>
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <SidebarProvider defaultOpen={true}>
        <MySidebar />
        <SidebarInset className="min-w-0">
          <div className="flex items-center gap-4 border-b px-4 py-2">
            <SidebarTrigger />
            <div className="flex-1">
              <NavigationMenuDemo />
            </div>
          </div>
          {children}
        </SidebarInset>
      </SidebarProvider>
    </ThemeProvider>
    </body>
  </html>
  );
}
